[package]
name = "tuxedo_sysfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio-uring = "0.3"
tokio = { version = "1", features = ["time"] }

tailor_api = { path = "../tailor_api" }

[dev-dependencies]
sudo = "0.6"