[package]
name = "tuxedo_sysfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "1"

[dev-dependencies]
sudo = "0.6"