[package]
name = "tailor_gui"
version = "0.1.0"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false
description = "Tailord GUI (part of tuxedo-rs)"
repository = "https://github.com/AaronErhardt/tuxedo-rs"

[dependencies]
futures = "0.3.26"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.17.0"
relm4-components = { version = "0.6.0-alpha.2", git = "https://github.com/Relm4/Relm4", branch = "next"}
relm4 = { version = "0.6.0-alpha.2", features = ["libadwaita", "gnome_44"], git = "https://github.com/Relm4/Relm4", branch = "next"}
tailor_api = "0.1"
tailor_client = "0.1"
tokio = { version = "1.25", features = ["parking_lot"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracker = "0.2"
