[package]
name = "tailor_gui"
version = "0.1.0"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = "0.1"
tracing-subscriber = "0.3"
relm4 = { features = ["libadwaita", "gnome_43"], version = "0.5.0-rc.2" }
relm4-components = "0.5.0-rc.2"

tracker = "0.2"

tailor_client = "0.1.8"
tailor_api = "0.1"
futures = "0.3.26"
once_cell = "1.17.0"

tokio = { version = "1.25", features = ["parking_lot"] }
