[package]
name = "tailor_gui"
version = "0.1.0"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = "0.1"
tracing-subscriber = "0.3"
relm4 = { version = "0.6.0-alpha.2", features = ["libadwaita", "gnome_44"], git = "https://github.com/Relm4/Relm4", branch = "next"}
relm4-components = { version = "0.6.0-alpha.2", git = "https://github.com/Relm4/Relm4", branch = "next"}

tracker = "0.2"

tailor_client = "0.1.8"
tailor_api = "0.1"
futures = "0.3.26"
once_cell = "1.17.0"

tokio = { version = "1.25", features = ["parking_lot"] }
