[package]
name = "tailor_gui"
version = "0.1.0"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = "0.1"
tracing-subscriber = "0.3"
relm4 = { features = ["libadwaita"], version = "0.5.0-beta.5" }
relm4-components = "0.5.0-beta.5"
adw = { package = "libadwaita", version = "0.2", features = ["v1_2"] }
gtk = { package = "gtk4", version = "0.5", features = ["v4_8"] }

tracker = "0.2"

tailor_client = "0.1.2"
tailor_api = "0.1"
futures = "0.3.24"
once_cell = "1.15.0"

tokio = { version = "1.0", features = ["parking_lot"] }