[package]
name = "tailor_gui"
version = "0.1.0"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
tracing = "0.1"
tracing-subscriber = "0.3"
relm4 = { git = "https://github.com/Relm4/Relm4", features = ["macros", "libadwaita"] }

tailor_client = "0.1.2"