name: "Nix build"
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#devShells.x86_64-linux.default
          - .#packages.x86_64-linux.tailord
          - .#packages.x86_64-linux.tailor_gui
          - .#checks.x86_64-linux.formatting
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: tuxedo-rs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build "${{matrix.attribute}}"
