name: "Nix build"
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#devShells.x86_64-linux.default
          - .#packages.x86_64-linux.tuxedo-rs
          - .#packages.x86_64-linux.tailor-gui
          - .#checks.x86_64-linux.formatting
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v14
    - name: Set up cachix
      uses: cachix/cachix-action@v15
      with:
        name: tuxedo-rs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build "${{matrix.attribute}}"
